tools: check tools that give version with -V

diff --git a/extras/tools/bootstrap b/extras/tools/bootstrap
--- a/extras/tools/bootstrap
+++ b/extras/tools/bootstrap
@@ -70,6 +70,14 @@ else
 fi
 }
 
+check_v() {
+if ! $1 -V 2>/dev/null
+then
+    echo "$1 not found"
+    NEEDED="$NEEDED .$1"
+fi
+}
+
 check autoconf 2.69
 check automake 1.15
 check m4 1.4.16
